import { LADDER } from "@/game/emails";
import { SEED_ROSTER } from "@/game/subjects";
import type {
  Action,
  Day,
  Email,
  Outcome,
  OutcomeKey,
  Resolution,
  RosterChange,
  RosterTransition,
  Situation,
  State,
  Tally,
} from "@/game/types";

export const EMPTY_TALLY: Tally = {
  verified: 0,
  errorsCaught: 0,
  errorsAccepted: 0,
  randomized: 0,
  harmed: 0,
};

export const initialState: State = {
  screen: "signin",
  day: 1,
  clock: 0,
  index: 0,
  resolutions: [],
  inbox: [],
  roster: SEED_ROSTER,
  dayRosterChanges: [],
  tally: EMPTY_TALLY,
};

export function situationById(id: string, script: Situation[]): Situation {
  const found = script.find((s) => s.id === id);
  if (!found) throw new Error(`Unknown situation: ${id}`);
  return found;
}

function addTally(tally: Tally, delta: Partial<Tally>): Tally {
  return {
    verified: tally.verified + (delta.verified ?? 0),
    errorsCaught: tally.errorsCaught + (delta.errorsCaught ?? 0),
    errorsAccepted: tally.errorsAccepted + (delta.errorsAccepted ?? 0),
    randomized: tally.randomized + (delta.randomized ?? 0),
    harmed: tally.harmed + (delta.harmed ?? 0),
  };
}

function valuesMatch(a: Record<string, string>, b: Record<string, string>): boolean {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  return [...keys].every((k) => (a[k] ?? "").trim() === (b[k] ?? "").trim());
}

/** Applies one resolution: appends it, adds its score, and advances the clock. */
function resolve(
  state: State,
  situation: Situation,
  resolution: Resolution,
  minutes: number,
  script: Situation[],
): State {
  const outcome: Outcome = situation.outcomes[resolution.outcomeKey];
  const index = state.index + 1;
  const next = script[index];
  const screen: State["screen"] = !next ? "ending" : next.day !== situation.day ? "dayend" : "desk";

  const resolved: State = {
    ...state,
    screen,
    index,
    clock: state.clock + minutes,
    resolutions: [...state.resolutions, resolution],
    tally: addTally(state.tally, outcome.score),
  };

  return closeDay(resolved, script);
}

function accept(state: State, script: Situation[]): State {
  const situation = script[state.index];
  const correct = situation.truth.error === "NONE";
  return resolve(
    state,
    situation,
    { situationId: situation.id, action: "accepted", correct, outcomeKey: "accepted" },
    30,
    script,
  );
}

export type DaySummary = {
  worked: { situation: Situation; resolution: Resolution }[];
  emails: Email[];
  rosterChanges: RosterChange[];
};

/** Everything that happened on `state.day`: what was worked, and the consequences it generated. */
export function summariseDay(state: State, script: Situation[]): DaySummary {
  const worked = state.resolutions
    .map((resolution) => ({ resolution, situation: situationById(resolution.situationId, script) }))
    .filter(({ situation }) => situation.day === state.day);

  const emails: Email[] = [];
  const rosterChanges: RosterChange[] = [];

  for (const { situation, resolution } of worked) {
    const outcome = situation.outcomes[resolution.outcomeKey];
    if (outcome.email) emails.push(outcome.email);
    if (outcome.roster) rosterChanges.push(outcome.roster);
  }

  return { worked, emails: [...emails, ...LADDER[state.day]], rosterChanges };
}

/** Applies every consequence generated by the closing day's resolutions. */
function applyConsequences(state: State, script: Situation[]): State {
  const { emails, rosterChanges } = summariseDay(state, script);

  // Recorded here, as each change is applied, because this is the only moment the roster's
  // prior status is still in hand — reconstructing it later by diffing would be a guess.
  const { roster, dayRosterChanges } = rosterChanges.reduce(
    (acc, change) => {
      const from = acc.roster.find((s) => s.id === change.subject)?.status ?? change.status;
      return {
        roster: acc.roster.map((s) =>
          s.id === change.subject ? { ...s, status: change.status } : s,
        ),
        dayRosterChanges: [
          ...acc.dayRosterChanges,
          { subject: change.subject, from, to: change.status },
        ],
      };
    },
    { roster: state.roster, dayRosterChanges: [] as RosterTransition[] },
  );

  return { ...state, roster, dayRosterChanges, inbox: [...state.inbox, ...emails] };
}

/**
 * Commits a day's consequences at the moment it actually closes — the transition into
 * "dayend" or "ending" — rather than waiting on a BEGIN_DAY that is not guaranteed to
 * follow (SKIP_DAY can jump straight to "ending", and there is no day after the last one).
 * A no-op otherwise, so it is safe to route every state-producing branch through it.
 */
function closeDay(state: State, script: Situation[]): State {
  if (state.screen !== "dayend" && state.screen !== "ending") return state;
  return applyConsequences(state, script);
}

export function reducer(state: State, action: Action, script: Situation[]): State {
  switch (action.type) {
    case "RESTORE":
      return action.state;

    case "SIGN_IN":
      return { ...state, screen: "desk" };

    case "ACCEPT":
      return accept(state, script);

    case "SUBMIT": {
      const situation = script[state.index];
      const valuesOk = valuesMatch(action.values, situation.truth.entry);
      const verdictOk =
        situation.truth.verdict === undefined ? true : action.verdict === situation.truth.verdict;
      const correct = valuesOk && verdictOk;
      const outcomeKey: OutcomeKey = correct ? "reviewedCorrect" : "reviewedWrong";

      return resolve(
        state,
        situation,
        {
          situationId: situation.id,
          action: "reviewed",
          submitted: action.values,
          verdict: action.verdict,
          correct,
          outcomeKey,
        },
        situation.cost,
        script,
      );
    }

    case "SKIP_DAY": {
      let next = state;
      while (script[next.index] && script[next.index].day === state.day) {
        next = accept(next, script);
      }
      return next;
    }

    case "BEGIN_DAY": {
      const day = (state.day + 1) as Day;
      return { ...state, screen: "desk", day, clock: 0 };
    }

    default:
      return state;
  }
}
