import { SEED_ROSTER } from "@/game/subjects";
import type {
  Action,
  Day,
  Outcome,
  OutcomeKey,
  Resolution,
  Situation,
  State,
  Tally,
} from "@/game/types";

export const EMPTY_TALLY: Tally = {
  verified: 0,
  errorsCaught: 0,
  errorsAccepted: 0,
  randomized: 0,
  harmed: 0,
};

export const initialState: State = {
  screen: "signin",
  day: 1,
  clock: 0,
  index: 0,
  resolutions: [],
  inbox: [],
  roster: SEED_ROSTER,
  tally: EMPTY_TALLY,
};

export function situationById(id: string, script: Situation[]): Situation {
  const found = script.find((s) => s.id === id);
  if (!found) throw new Error(`Unknown situation: ${id}`);
  return found;
}

function addTally(tally: Tally, delta: Partial<Tally>): Tally {
  return {
    verified: tally.verified + (delta.verified ?? 0),
    errorsCaught: tally.errorsCaught + (delta.errorsCaught ?? 0),
    errorsAccepted: tally.errorsAccepted + (delta.errorsAccepted ?? 0),
    randomized: tally.randomized + (delta.randomized ?? 0),
    harmed: tally.harmed + (delta.harmed ?? 0),
  };
}

function valuesMatch(a: Record<string, string>, b: Record<string, string>): boolean {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  return [...keys].every((k) => (a[k] ?? "").trim() === (b[k] ?? "").trim());
}

/** Applies one resolution: appends it, adds its score, and advances the clock. */
function resolve(
  state: State,
  situation: Situation,
  resolution: Resolution,
  minutes: number,
  script: Situation[],
): State {
  const outcome: Outcome = situation.outcomes[resolution.outcomeKey];
  const index = state.index + 1;
  const next = script[index];
  const screen: State["screen"] = !next ? "ending" : next.day !== situation.day ? "dayend" : "desk";

  return {
    ...state,
    screen,
    index,
    clock: state.clock + minutes,
    resolutions: [...state.resolutions, resolution],
    tally: addTally(state.tally, outcome.score),
  };
}

function accept(state: State, script: Situation[]): State {
  const situation = script[state.index];
  const correct = situation.truth.error === "NONE";
  return resolve(
    state,
    situation,
    { situationId: situation.id, action: "accepted", correct, outcomeKey: "accepted" },
    30,
    script,
  );
}

/** Applies every consequence generated by `day`'s resolutions. */
function applyConsequences(state: State, day: Day, script: Situation[]): State {
  const relevant = state.resolutions.filter(
    (r) => situationById(r.situationId, script).day === day,
  );

  let roster = state.roster;
  const emails = [...state.inbox];

  for (const r of relevant) {
    const outcome = situationById(r.situationId, script).outcomes[r.outcomeKey];
    if (outcome.email) emails.push(outcome.email);
    if (outcome.roster) {
      const change = outcome.roster;
      roster = roster.map((s) =>
        s.id === change.subject ? { ...s, status: change.status } : s,
      );
    }
  }

  return { ...state, roster, inbox: emails };
}

export function reducer(state: State, action: Action, script: Situation[]): State {
  switch (action.type) {
    case "SIGN_IN":
      return { ...state, screen: "desk" };

    case "ACCEPT":
      return accept(state, script);

    case "SUBMIT": {
      const situation = script[state.index];
      const valuesOk = valuesMatch(action.values, situation.truth.entry);
      const verdictOk = situation.truth.verdict === undefined
        ? true
        : action.verdict === situation.truth.verdict;
      const correct = valuesOk && verdictOk;
      const outcomeKey: OutcomeKey = correct ? "reviewedCorrect" : "reviewedWrong";

      return resolve(
        state,
        situation,
        {
          situationId: situation.id,
          action: "reviewed",
          submitted: action.values,
          verdict: action.verdict,
          correct,
          outcomeKey,
        },
        situation.cost,
        script,
      );
    }

    case "SKIP_DAY": {
      let next = state;
      while (script[next.index] && script[next.index].day === state.day) {
        next = accept(next, script);
      }
      return { ...next, screen: script[next.index] ? "dayend" : "ending" };
    }

    case "BEGIN_DAY": {
      const day = (state.day + 1) as Day;
      const withConsequences = applyConsequences(state, state.day, script);
      return { ...withConsequences, screen: "desk", day, clock: 0 };
    }

    default:
      return state;
  }
}
