import { describe, expect, it } from "vitest";

import { FIXTURE_SCRIPT } from "@/game/fixtures";
import { initialState, reducer, summariseDay } from "@/game/state";
import type { State } from "@/game/types";

const played = (...actions: Parameters<typeof reducer>[1][]): State =>
  actions.reduce((s, a) => reducer(s, a, FIXTURE_SCRIPT), {
    ...initialState,
    screen: "desk",
  } as State);

describe("summariseDay", () => {
  it("lists what was worked today, in order", () => {
    const s = played({ type: "ACCEPT" }, { type: "ACCEPT" });
    const summary = summariseDay(s, FIXTURE_SCRIPT);

    expect(summary.worked.map((w) => w.situation.id)).toEqual(["FIX-001", "FIX-002"]);
  });

  it("includes the day's ladder rung", () => {
    const s = played({ type: "ACCEPT" }, { type: "ACCEPT" });
    expect(summariseDay(s, FIXTURE_SCRIPT).emails.map((e) => e.id)).toContain("ENR-1");
  });

  it("includes emails generated by today's decisions", () => {
    const s = played(
      { type: "SUBMIT", values: { bp: "wrong", pulse: "wrong" } },
      { type: "ACCEPT" },
    );
    expect(summariseDay(s, FIXTURE_SCRIPT).emails.map((e) => e.id)).toContain("DQ-0111");
  });

  it("collects roster changes caused by today's decisions", () => {
    const s = played(
      { type: "ACCEPT" },
      { type: "ACCEPT" },
      { type: "BEGIN_DAY" },
      { type: "ACCEPT" },
    );
    expect(summariseDay(s, FIXTURE_SCRIPT).rosterChanges).toEqual([
      { subject: "1047-019", status: "Enrolled" },
    ]);
  });

  it("does not report yesterday's work as today's", () => {
    const s = played(
      { type: "ACCEPT" },
      { type: "ACCEPT" },
      { type: "BEGIN_DAY" },
      { type: "ACCEPT" },
    );
    expect(summariseDay(s, FIXTURE_SCRIPT).worked).toHaveLength(1);
  });
});
